// <auto-generated />
using System;
using Airdnd.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Airdnd.Migrations
{
    [DbContext(typeof(AirdndContext))]
    [Migration("20251116040349_Phase3_Admin_Validation")]
    partial class Phase3_Admin_Validation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("Airdnd.Models.Location", b =>
                {
                    b.Property<string>("LocationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LocationId");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            LocationId = "chicago",
                            Name = "Chicago"
                        },
                        new
                        {
                            LocationId = "atlanta",
                            Name = "Atlanta"
                        },
                        new
                        {
                            LocationId = "miami",
                            Name = "Miami"
                        },
                        new
                        {
                            LocationId = "nyc",
                            Name = "New York"
                        });
                });

            modelBuilder.Entity("Airdnd.Models.Reservation", b =>
                {
                    b.Property<int>("ReservationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ReservationEndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ReservationStartDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("ResidenceId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ReservationId");

                    b.HasIndex("ResidenceId");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("Airdnd.Models.Residence", b =>
                {
                    b.Property<int>("ResidenceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("BathroomNumber")
                        .HasColumnType("REAL");

                    b.Property<int>("BedroomNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BuiltYear")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GuestNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LocationId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("PricePerNight")
                        .HasColumnType("REAL");

                    b.Property<string>("ResidencePicture")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ResidenceId");

                    b.HasIndex("LocationId");

                    b.HasIndex("UserId");

                    b.ToTable("Residences");

                    b.HasData(
                        new
                        {
                            ResidenceId = 1,
                            BathroomNumber = 2.0,
                            BedroomNumber = 2,
                            BuiltYear = 2010,
                            GuestNumber = 4,
                            LocationId = "chicago",
                            Name = "Chicago Loop Apartment",
                            PricePerNight = 250.0,
                            ResidencePicture = "chicago_apt.jpg",
                            UserId = 1
                        },
                        new
                        {
                            ResidenceId = 2,
                            BathroomNumber = 3.0,
                            BedroomNumber = 4,
                            BuiltYear = 1995,
                            GuestNumber = 8,
                            LocationId = "atlanta",
                            Name = "Atlanta Suburban House",
                            PricePerNight = 320.0,
                            ResidencePicture = "atlanta_house.jpg",
                            UserId = 1
                        },
                        new
                        {
                            ResidenceId = 3,
                            BathroomNumber = 4.5,
                            BedroomNumber = 5,
                            BuiltYear = 2018,
                            GuestNumber = 10,
                            LocationId = "miami",
                            Name = "Miami Beach House",
                            PricePerNight = 700.0,
                            ResidencePicture = "miami_house.jpg",
                            UserId = 1
                        },
                        new
                        {
                            ResidenceId = 4,
                            BathroomNumber = 1.0,
                            BedroomNumber = 1,
                            BuiltYear = 1980,
                            GuestNumber = 2,
                            LocationId = "nyc",
                            Name = "NYC Studio",
                            PricePerNight = 180.0,
                            ResidencePicture = "nyc_studio.jpg",
                            UserId = 1
                        });
                });

            modelBuilder.Entity("Airdnd.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DOB")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("SSN")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            DOB = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "owner@airdnd.com",
                            Name = "Admin Owner",
                            UserType = "Owner"
                        },
                        new
                        {
                            UserId = 2,
                            DOB = new DateTime(1995, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "client@test.com",
                            Name = "Test Client",
                            UserType = "Client"
                        });
                });

            modelBuilder.Entity("Airdnd.Models.Reservation", b =>
                {
                    b.HasOne("Airdnd.Models.Residence", "Residence")
                        .WithMany()
                        .HasForeignKey("ResidenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Residence");
                });

            modelBuilder.Entity("Airdnd.Models.Residence", b =>
                {
                    b.HasOne("Airdnd.Models.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Airdnd.Models.User", "Owner")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");

                    b.Navigation("Owner");
                });
#pragma warning restore 612, 618
        }
    }
}
