// <auto-generated />
using System;
using Airdnd.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Airdnd.Migrations
{
    [DbContext(typeof(AirdndContext))]
    partial class AirdndContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("Airdnd.Models.Client", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DOB")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("Airdnd.Models.Location", b =>
                {
                    b.Property<string>("LocationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LocationId");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            LocationId = "chicago",
                            Name = "Chicago"
                        },
                        new
                        {
                            LocationId = "atlanta",
                            Name = "Atlanta"
                        },
                        new
                        {
                            LocationId = "miami",
                            Name = "Miami"
                        },
                        new
                        {
                            LocationId = "nyc",
                            Name = "New York"
                        });
                });

            modelBuilder.Entity("Airdnd.Models.Reservation", b =>
                {
                    b.Property<int>("ReservationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ReservationEndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ReservationStartDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("ResidenceId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ReservationId");

                    b.HasIndex("ResidenceId");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("Airdnd.Models.Residence", b =>
                {
                    b.Property<int>("ResidenceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BathroomNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BedroomNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GuestNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LocationId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("PricePerNight")
                        .HasColumnType("REAL");

                    b.Property<string>("ResidencePicture")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ResidenceId");

                    b.HasIndex("LocationId");

                    b.ToTable("Residences");

                    b.HasData(
                        new
                        {
                            ResidenceId = 1,
                            BathroomNumber = 2,
                            BedroomNumber = 2,
                            GuestNumber = 4,
                            LocationId = "chicago",
                            Name = "Chicago Loop Apartment",
                            PricePerNight = 250.0,
                            ResidencePicture = "chicago_apt.jpg"
                        },
                        new
                        {
                            ResidenceId = 2,
                            BathroomNumber = 3,
                            BedroomNumber = 4,
                            GuestNumber = 8,
                            LocationId = "atlanta",
                            Name = "Atlanta Suburban House",
                            PricePerNight = 320.0,
                            ResidencePicture = "atlanta_house.jpg"
                        },
                        new
                        {
                            ResidenceId = 3,
                            BathroomNumber = 4,
                            BedroomNumber = 5,
                            GuestNumber = 10,
                            LocationId = "miami",
                            Name = "Miami Beach House",
                            PricePerNight = 700.0,
                            ResidencePicture = "miami_house.jpg"
                        },
                        new
                        {
                            ResidenceId = 4,
                            BathroomNumber = 1,
                            BedroomNumber = 1,
                            GuestNumber = 2,
                            LocationId = "nyc",
                            Name = "NYC Studio",
                            PricePerNight = 180.0,
                            ResidencePicture = "nyc_studio.jpg"
                        });
                });

            modelBuilder.Entity("Airdnd.Models.Reservation", b =>
                {
                    b.HasOne("Airdnd.Models.Residence", "Residence")
                        .WithMany()
                        .HasForeignKey("ResidenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Residence");
                });

            modelBuilder.Entity("Airdnd.Models.Residence", b =>
                {
                    b.HasOne("Airdnd.Models.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");
                });
#pragma warning restore 612, 618
        }
    }
}
